### PR TITLE
Fixes #6359: Include check-rudder-agent in rudder cli

### PR DESCRIPTION
**Pull request by peckpeck**
https://www.rudder-project.org/redmine/issues/6359

Replacing previous PR: https://github.com/Normation/rudder-agent/pull/9

### CODE REVIEW

**Comment by amousset** [comment]
A more detailed description in @man could be useful, especially as this command does more than just a check.

**Comment by Kegeruneku** [comment]
Eeyup !

**Comment by peckpeck** [comment]
PR updated

**Comment by Kegeruneku** [comment]
Accepted

**Pull request merged**
