### PR TITLE
Fixes #20331: Don't use a passphrase anymore in agent check

### PR DESCRIPTION
**Pull request by amousset**
https://issues.rudder.io/issues/20331

### CODE REVIEW

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Review by peckpeck — APPROVED** [review]

**Comment by amousset** [comment]
OK, squash merging this PR

**Pull request merged**
