### PR TITLE
Fixes #9241: Add new audit reports type to rudder command

### PR DESCRIPTION
**Pull request by amousset**
https://www.rudder-project.org/redmine/issues/9241

### CODE REVIEW

**Comment by amousset** [comment]
This is how it lokks like:
auditlog

Still a few questions:
* Which colors to use? It would be good to use the same as in the interface, but ANSI colors are quite limited.
* How do we want to name audit error (which do not exist for now) in the output? For now they are merged into the global error report.
* Do we want to separate audit and enforce in the summary?

**Comment by peckpeck** [comment]
I don't have a good answer to this.
* which colors: if you want different colors for audit and enforce, you need 4 colors, and green/red are the only one with implicit meaning
* audit errors are exactly like enforce errors: errors
* when you say separate you mean output them separately ? then i'd say no

**Comment by jooooooon** [comment]
Color wise, the green and red look very close to the green and red we use already, so that's great. "non-compliant" should, in my opinion, be orange - it's a warning, not an error.

"error" is an error, as @peckpeck says, but it could be useful for debugging to figure out whether that component was trying to audit or to enforce. I'm tempted to suggest "error (audit)" and "error (enforce)"?

However, I'm also tempted to say that "success" (what a terrible name) and "compliant" mean the same thing - we checked something and it was already ok, so didn't do anything, and that we should probably merge them. That would make sense in the summary at the end too.

So, in light of that, maybe we could prefix each line with an extra column with "A" (for Audit) or "E" (for Enforce) in blue and green, respectively. That way, "error" will be sufficient, and "compliant" will be too. Obviously "repaired" and "non compliant" would only ever appear in E and A modes respectively, but that's OK. WDYT?

**Comment by amousset** [comment]
log

**Comment by peckpeck** [comment]
You have empty space at the begining, it could be reduced, or it could be used to have a 3 letter version of enforce/audit tag which can be more helpful for the user who doesn't know what the letters mean.

**Comment by amousset** [comment]
Now with merged success/compliant, and tried complete word for mode:
log3

**Comment by amousset** [comment]
I agree that "success" is a bad name, but we would need to change it everywhere in the interface too.
We don't have orange in ANSI colors, so I used magenta for non-compliance, as for `log_warn`.

**Comment by peckpeck** [comment]
Sorry for changing opinion, but the long form seems too long now.
I don't have definite preference between both now.

**Comment by amousset** [comment]
With the mode between brackets:
log4

**Comment by amousset** [comment]
Commit modified

**Comment by peckpeck** [comment]
I'd say better

**Comment by jooooooon** [comment]
Looking good! I like the idea of using "AUD" and "ENF" as 3 letter abbreviations, actually. It seems easier to understand than a single letter.

**Comment by amousset** [comment]
With a backgroud:
log6

**Comment by amousset** [comment]
Same with 3 letters for mode:
log7

**Comment by peckpeck** [comment]
I don't like the background version

**Comment by jooooooon** [comment]
I like it! The background is great, and the 3 letters seem clear to me.

**Comment by ncharles** [comment]
Same as @peckpeck , I don't really like the background (reminds me of old Apple II output, when something was wrong)

**Comment by VinceMacBuche** [comment]
Like the background but prefer with one letter

**Comment by jooooooon** [comment]
Actually the caps "AUD" and "ENF" make it look a lot like the output from a AS/400 system or something. Maybe try "Aud" and "Enf" ?

**Comment by Kegeruneku** [comment]
Like the background but prefer with one letter too !

**Comment by amousset** [comment]
With Aud and Enf:
log8

**Comment by amousset** [comment]
I don't really like aud/anf, I don't fell it makes more sense than a letter at first sight. I think we should either write it completely or find another way. I like the background because the meaning is clear once someone knows to the Rudder web interface because it maps directly to the mode tags on nodes/directives/rules.

**Comment by Kegeruneku** [comment]
Angry Clint

So you like emojis that much, punk ?

**Comment by Kegeruneku** [comment]
Angry Samuel

Use another emoji, I dare you, I double dare you muthaf*ck*r!!!

**Comment by amousset** [comment]
With a light text and no background:
log9

**Comment by ncharles** [comment]
3 letters are too short indeed - a user who did not read the doc or changelog before updating might get confused. So using the full word would me more readable
A full background is kind of acceptable will non-capital letter, but it's readability is poor compared to the non-backgrounded approach

**Comment by ncharles** [comment]
Oh, a one letter, plus in the summary a summary of the total of Audit and Enforce, so that it's self explanatory ?

**Comment by amousset** [comment]
Integrated in the result column:

log10

**Comment by peckpeck** [comment]
I like it better

**Comment by ncharles** [comment]
I'm not keen on the /

**Comment by amousset** [comment]
Another try with the convention of | for cut string, showing full line when calling with -w.
log12

**Comment by ncharles** [comment]
I like this one. If the summary could include the number of Enforce and Audit, you'd make me an happy man

**Comment by amousset** [comment]
Do you think a global count makes sense? Should we have subtotal by mode or by result?

**Comment by Kegeruneku** [comment]
Agreed with @ncharles

**Comment by amousset** [comment]
Commit modified

**Comment by ncharles** [comment]
@amousset probably both - number of audit, number of enforce

**Comment by amousset** [comment]
Commit modified

**Comment by amousset** [comment]
Commit modified

**Comment by jooooooon** [comment]
I think that if the -w switch is not given, and we display "A" and "E" we should use the summary to clarify what A and E stand for, a bit like a legend for a map/chart.

I can see the summary ideally as something like this:
X rules, Y directives, Z components verified
A components in Audit mode: B compliant, C non-compliant, D error
A2 components in Enforce mode: B2 compliant, C2 repaired, D2 error

(where "Audit" is written as the same color as in the lines in the main output)

**Comment by amousset** [comment]
Commit modified

**Comment by amousset** [comment]
Tried with counts on a line:
sum

But I do not find it very readable, tried something else:

summary

**Comment by VinceMacBuche** [comment]
Would be great if they are aligned at least all on the left

```
components:
audit mode component:
compliant:
non-compliant:
error:
n/a:
```

even greater if colon are aligned:

```
components                 :
audit mode component:
compliant                     :
non-compliant              :
error                             :
n/a                                :
```

Maybe if you want the last four shifted:

```
components                 :
audit mode component:
 * compliant                  :
 * non-compliant           :  
 * error                          :
 * n/a                             :
```

(Maybe not a star but something else)

**Comment by amousset** [comment]
With alignment on the left and a hierarchical view:

hier

**Comment by amousset** [comment]
I will try putting the numbers first.

**Comment by amousset** [comment]
sum42

**Comment by amousset** [comment]
Commit modified

**Comment by VinceMacBuche** [comment]
I like the last one !

**Comment by ncharles** [comment]
awesomeness overflow

**Comment by amousset** [comment]
Commit modified

**Comment by amousset** [comment]
Commit modified

**Comment by amousset** [comment]
* Did some refactoring in the general code, it was beginning to be quite unreadable
* Renamed *Result* to *State*

run

**Comment by amousset** [comment]
Commit modified

**Comment by peckpeck** [comment]
👍

**Comment by amousset** [comment]
Commit modified

**Comment by amousset** [comment]
Commit modified

**Pull request merged**
