### PR TITLE
Fixes #6543: Add a rudder remote run command

### PR DESCRIPTION
**Pull request by peckpeck**
http://www.rudder-project.org/redmine/issues/6543

### CODE REVIEW

**Comment by amousset** [comment]
OK for me, but cannot be merged while https://github.com/Normation/rudder-techniques/pull/663 is not merged.

**Comment by peckpeck** [comment]
It can be merged without breaking anything because the command will be called by a user whenever he wants it. If the corresponding node doesn't accept the connection, it will be as is it was on an older version of rudder and just give back an error.

**Comment by peckpeck** [comment]
Ping @VinceMacBuche #663 has been merged

**Comment by VinceMacBuche** [comment]
Great!

**Pull request merged**
