### PR TITLE
Patch to use rudder on a read-only / system (move /var/rudder and /opt/rudder to another directories)

### PR DESCRIPTION
**Pull request by Thus0**
I want to use rudder on a read-only rootfs embedded device (/var/rudder is readonly) so I need to move /var/rudder to another writable directory.

Changes made :
  - replace static /var/rudder/ by ${RUDDER_VAR}
  - replace static /opt/rudder/ by ${RUDDER_DIR}

### CODE REVIEW

**Comment by peckpeck** [comment]
Hi,
Thank you for the contribution.
You need to define a default value for those variables otherwise it will fail to work for existing users. I'd say to do it in common.sh

Then, be aware that this is just a first step, there are many places in rudder where those paths are hardcoded

**Comment by Thus0** [comment]
> You need to define a default value for those variables otherwise it will fail to work for existing users. I'd say to do it in common.sh

Indeed, I've use the already existing variables RUDDER_VAR and RUDDER_DIR which are defined in `share/lib/common.sh` and common.sh is sourced by all scripts in `share/commands/*` ; so it should (normally) not break things.


@peckpeck : on my node (it's an arm device), should I need other things other than "rudder-agent" ? I'm new to rudder and will try to test it on an embedded linux.

Pierre

**Comment by peckpeck** [comment]
You don't need any other package that rudder-agent, but you are given policies from the rudder server that contain such hardcoded paths.

**Comment by peckpeck** [comment]
I forgot these variabes already existed, so it's a good thing :+1:

**Comment by peckpeck** [comment]
Thank you for the sed rules.
I understand that the hook could work for you, but i don't think we could do it within rudder without subtly breaking things.

I think another way to do it on your system could be to replace /var/rudder and /opt/rudder by symlinks to the  final path of your choice.

**Comment by peckpeck** [comment]
in fact i would still appreciate merging this PR, since having variables here is a good thing for our code

**Review by peckpeck — APPROVED** [review]

**Pull request merged**
